//package parser;
//import javax.sound.midi.Sequence;
////testing commits
////testing commits using IDE
////Team member mo pushed a change
//import javax.xml.parsers.*;
//import org.xml.sax.InputSource;
//
//import com.fasterxml.jackson.core.JsonProcessingException;
//import com.fasterxml.jackson.databind.ObjectMapper;
//import com.fasterxml.jackson.dataformat.xml.XmlMapper;
//
//import models.ScorePartwise;
//import nu.xom.ParsingException;
//import nu.xom.ValidityException;
//
//import org.jfugue.integration.LilyPondParserListener;
//import org.jfugue.integration.MusicXmlParser;
//import org.jfugue.integration.MusicXmlParserListener;
//import org.jfugue.midi.MidiParserListener;
//import org.jfugue.pattern.Pattern;
//import org.jfugue.player.Player;
//import org.staccato.StaccatoParserListener;
//import org.w3c.dom.*;
//import java.io.*;
//
////testing push before pull
//public class ParserConsole {
//	static String xmlString = "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"no\"?>\n"
//			+ "<!DOCTYPE score-partwise PUBLIC \"-//Recordare//DTD MusicXML 3.1 Partwise//EN\" \"http://www.musicxml.org/dtds/partwise.dtd\">\n"
//			+ "<score-partwise version=\"3.1\">\n"
//			+ "  <identification>\n"
//			+ "    <creator type=\"composer\"></creator>\n"
//			+ "  </identification>\n"
//			+ "  <part-list>\n"
//			+ "    <score-part id=\"P1\">\n"
//			+ "      <part-name>Guitar</part-name>\n"
//			+ "    </score-part>\n"
//			+ "  </part-list>\n"
//			+ "  <part id=\"P1\">\n"
//			+ "    <measure number=\"1\">\n"
//			+ "      <attributes>\n"
//			+ "        <divisions>16</divisions>\n"
//			+ "        <key>\n"
//			+ "          <fifths>0</fifths>\n"
//			+ "        </key>\n"
//			+ "        <clef>\n"
//			+ "          <sign>TAB</sign>\n"
//			+ "          <line>5</line>\n"
//			+ "        </clef>\n"
//			+ "        <staff-details>\n"
//			+ "          <staff-lines>6</staff-lines>\n"
//			+ "          <staff-tuning line=\"1\">\n"
//			+ "            <tuning-step>E</tuning-step>\n"
//			+ "            <tuning-octave>2</tuning-octave>\n"
//			+ "          </staff-tuning>\n"
//			+ "          <staff-tuning line=\"2\">\n"
//			+ "            <tuning-step>A</tuning-step>\n"
//			+ "            <tuning-octave>2</tuning-octave>\n"
//			+ "          </staff-tuning>\n"
//			+ "          <staff-tuning line=\"3\">\n"
//			+ "            <tuning-step>D</tuning-step>\n"
//			+ "            <tuning-octave>3</tuning-octave>\n"
//			+ "          </staff-tuning>\n"
//			+ "          <staff-tuning line=\"4\">\n"
//			+ "            <tuning-step>G</tuning-step>\n"
//			+ "            <tuning-octave>3</tuning-octave>\n"
//			+ "          </staff-tuning>\n"
//			+ "          <staff-tuning line=\"5\">\n"
//			+ "            <tuning-step>B</tuning-step>\n"
//			+ "            <tuning-octave>3</tuning-octave>\n"
//			+ "          </staff-tuning>\n"
//			+ "          <staff-tuning line=\"6\">\n"
//			+ "            <tuning-step>E</tuning-step>\n"
//			+ "            <tuning-octave>4</tuning-octave>\n"
//			+ "          </staff-tuning>\n"
//			+ "        </staff-details>\n"
//			+ "      </attributes>\n"
//			+ "      <note>\n"
//			+ "        <pitch>\n"
//			+ "          <step>E</step>\n"
//			+ "          <octave>2</octave>\n"
//			+ "        </pitch>\n"
//			+ "        <duration>8</duration>\n"
//			+ "        <voice>1</voice>\n"
//			+ "        <type>eighth</type>\n"
//			+ "        <notations>\n"
//			+ "          <technical>\n"
//			+ "            <string>6</string>\n"
//			+ "            <fret>0</fret>\n"
//			+ "          </technical>\n"
//			+ "        </notations>\n"
//			+ "      </note>\n"
//			+ "      <note>\n"
//			+ "        <pitch>\n"
//			+ "          <step>B</step>\n"
//			+ "          <octave>2</octave>\n"
//			+ "        </pitch>\n"
//			+ "        <duration>8</duration>\n"
//			+ "        <voice>1</voice>\n"
//			+ "        <type>eighth</type>\n"
//			+ "        <notations>\n"
//			+ "          <technical>\n"
//			+ "            <string>5</string>\n"
//			+ "            <fret>2</fret>\n"
//			+ "          </technical>\n"
//			+ "        </notations>\n"
//			+ "      </note>\n"
//			+ "      <note>\n"
//			+ "        <pitch>\n"
//			+ "          <step>E</step>\n"
//			+ "          <octave>3</octave>\n"
//			+ "        </pitch>\n"
//			+ "        <duration>8</duration>\n"
//			+ "        <voice>1</voice>\n"
//			+ "        <type>eighth</type>\n"
//			+ "        <notations>\n"
//			+ "          <technical>\n"
//			+ "            <string>4</string>\n"
//			+ "            <fret>2</fret>\n"
//			+ "          </technical>\n"
//			+ "        </notations>\n"
//			+ "      </note>\n"
//			+ "      <note>\n"
//			+ "        <pitch>\n"
//			+ "          <step>G</step>\n"
//			+ "          <alter>1</alter>\n"
//			+ "          <octave>3</octave>\n"
//			+ "        </pitch>\n"
//			+ "        <duration>8</duration>\n"
//			+ "        <voice>1</voice>\n"
//			+ "        <type>eighth</type>\n"
//			+ "        <notations>\n"
//			+ "          <technical>\n"
//			+ "            <string>3</string>\n"
//			+ "            <fret>1</fret>\n"
//			+ "          </technical>\n"
//			+ "        </notations>\n"
//			+ "      </note>\n"
//			+ "      <note>\n"
//			+ "        <pitch>\n"
//			+ "          <step>B</step>\n"
//			+ "          <octave>3</octave>\n"
//			+ "        </pitch>\n"
//			+ "        <duration>8</duration>\n"
//			+ "        <voice>1</voice>\n"
//			+ "        <type>eighth</type>\n"
//			+ "        <notations>\n"
//			+ "          <technical>\n"
//			+ "            <string>2</string>\n"
//			+ "            <fret>0</fret>\n"
//			+ "          </technical>\n"
//			+ "        </notations>\n"
//			+ "      </note>\n"
//			+ "      <note>\n"
//			+ "        <pitch>\n"
//			+ "          <step>E</step>\n"
//			+ "          <octave>4</octave>\n"
//			+ "        </pitch>\n"
//			+ "        <duration>8</duration>\n"
//			+ "        <voice>1</voice>\n"
//			+ "        <type>eighth</type>\n"
//			+ "        <notations>\n"
//			+ "          <technical>\n"
//			+ "            <string>1</string>\n"
//			+ "            <fret>0</fret>\n"
//			+ "          </technical>\n"
//			+ "        </notations>\n"
//			+ "      </note>\n"
//			+ "      <note>\n"
//			+ "        <pitch>\n"
//			+ "          <step>B</step>\n"
//			+ "          <octave>3</octave>\n"
//			+ "        </pitch>\n"
//			+ "        <duration>8</duration>\n"
//			+ "        <voice>1</voice>\n"
//			+ "        <type>eighth</type>\n"
//			+ "        <notations>\n"
//			+ "          <technical>\n"
//			+ "            <string>2</string>\n"
//			+ "            <fret>0</fret>\n"
//			+ "          </technical>\n"
//			+ "        </notations>\n"
//			+ "      </note>\n"
//			+ "      <note>\n"
//			+ "        <pitch>\n"
//			+ "          <step>G</step>\n"
//			+ "          <alter>1</alter>\n"
//			+ "          <octave>3</octave>\n"
//			+ "        </pitch>\n"
//			+ "        <duration>8</duration>\n"
//			+ "        <voice>1</voice>\n"
//			+ "        <type>eighth</type>\n"
//			+ "        <notations>\n"
//			+ "          <technical>\n"
//			+ "            <string>3</string>\n"
//			+ "            <fret>1</fret>\n"
//			+ "          </technical>\n"
//			+ "        </notations>\n"
//			+ "      </note>\n"
//			+ "    </measure>\n"
//			+ "    <measure number=\"2\">\n"
//			+ "      <attributes>\n"
//			+ "        <divisions>16</divisions>\n"
//			+ "        <key>\n"
//			+ "          <fifths>0</fifths>\n"
//			+ "        </key>\n"
//			+ "      </attributes>\n"
//			+ "      <note>\n"
//			+ "        <pitch>\n"
//			+ "          <step>E</step>\n"
//			+ "          <octave>4</octave>\n"
//			+ "        </pitch>\n"
//			+ "        <duration>64</duration>\n"
//			+ "        <voice>1</voice>\n"
//			+ "        <type>whole</type>\n"
//			+ "        <notations>\n"
//			+ "          <technical>\n"
//			+ "            <string>1</string>\n"
//			+ "            <fret>0</fret>\n"
//			+ "          </technical>\n"
//			+ "        </notations>\n"
//			+ "      </note>\n"
//			+ "      <note>\n"
//			+ "        <chord/>\n"
//			+ "        <pitch>\n"
//			+ "          <step>B</step>\n"
//			+ "          <octave>3</octave>\n"
//			+ "        </pitch>\n"
//			+ "        <duration>64</duration>\n"
//			+ "        <voice>1</voice>\n"
//			+ "        <type>whole</type>\n"
//			+ "        <notations>\n"
//			+ "          <technical>\n"
//			+ "            <string>2</string>\n"
//			+ "            <fret>0</fret>\n"
//			+ "          </technical>\n"
//			+ "        </notations>\n"
//			+ "      </note>\n"
//			+ "      <note>\n"
//			+ "        <chord/>\n"
//			+ "        <pitch>\n"
//			+ "          <step>G</step>\n"
//			+ "          <alter>1</alter>\n"
//			+ "          <octave>3</octave>\n"
//			+ "        </pitch>\n"
//			+ "        <duration>64</duration>\n"
//			+ "        <voice>1</voice>\n"
//			+ "        <type>whole</type>\n"
//			+ "        <notations>\n"
//			+ "          <technical>\n"
//			+ "            <string>3</string>\n"
//			+ "            <fret>1</fret>\n"
//			+ "          </technical>\n"
//			+ "        </notations>\n"
//			+ "      </note>\n"
//			+ "      <note>\n"
//			+ "        <chord/>\n"
//			+ "        <pitch>\n"
//			+ "          <step>E</step>\n"
//			+ "          <octave>3</octave>\n"
//			+ "        </pitch>\n"
//			+ "        <duration>64</duration>\n"
//			+ "        <voice>1</voice>\n"
//			+ "        <type>whole</type>\n"
//			+ "        <notations>\n"
//			+ "          <technical>\n"
//			+ "            <string>4</string>\n"
//			+ "            <fret>2</fret>\n"
//			+ "          </technical>\n"
//			+ "        </notations>\n"
//			+ "      </note>\n"
//			+ "      <note>\n"
//			+ "        <chord/>\n"
//			+ "        <pitch>\n"
//			+ "          <step>B</step>\n"
//			+ "          <octave>2</octave>\n"
//			+ "        </pitch>\n"
//			+ "        <duration>64</duration>\n"
//			+ "        <voice>1</voice>\n"
//			+ "        <type>whole</type>\n"
//			+ "        <notations>\n"
//			+ "          <technical>\n"
//			+ "            <string>5</string>\n"
//			+ "            <fret>2</fret>\n"
//			+ "          </technical>\n"
//			+ "        </notations>\n"
//			+ "      </note>\n"
//			+ "      <note>\n"
//			+ "        <chord/>\n"
//			+ "        <pitch>\n"
//			+ "          <step>E</step>\n"
//			+ "          <octave>2</octave>\n"
//			+ "        </pitch>\n"
//			+ "        <duration>64</duration>\n"
//			+ "        <voice>1</voice>\n"
//			+ "        <type>whole</type>\n"
//			+ "        <notations>\n"
//			+ "          <technical>\n"
//			+ "            <string>6</string>\n"
//			+ "            <fret>0</fret>\n"
//			+ "          </technical>\n"
//			+ "        </notations>\n"
//			+ "      </note>\n"
//			+ "    </measure>\n"
//			+ "  </part>\n"
//			+ "</score-partwise>\n"
//			+ "\n";
//	static String drum = "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"no\"?>\r\n"
//			+ "<!DOCTYPE score-partwise PUBLIC \"-//Recordare//DTD MusicXML 3.1 Partwise//EN\" \"http://www.musicxml.org/dtds/partwise.dtd\">\r\n"
//			+ "<score-partwise version=\"3.1\">\r\n"
//			+ "  <identification>\r\n"
//			+ "    <creator type=\"composer\"></creator>\r\n"
//			+ "  </identification>\r\n"
//			+ "  <part-list>\r\n"
//			+ "    <score-part id=\"P1\">\r\n"
//			+ "      <part-name>Drumset</part-name>\r\n"
//			+ "      <score-instrument>\r\n"
//			+ "        <score-instrument id=\"P1-I52\">\r\n"
//			+ "          <instrument-name>Ride Cymbal 1</instrument-name>\r\n"
//			+ "        </score-instrument>\r\n"
//			+ "        <score-instrument id=\"P1-I42\">\r\n"
//			+ "          <instrument-name>Low Floor Tom</instrument-name>\r\n"
//			+ "        </score-instrument>\r\n"
//			+ "        <score-instrument id=\"P1-I47\">\r\n"
//			+ "          <instrument-name>Open Hi-Hat</instrument-name>\r\n"
//			+ "        </score-instrument>\r\n"
//			+ "        <score-instrument id=\"P1-I43\">\r\n"
//			+ "          <instrument-name>Closed Hi-Hat</instrument-name>\r\n"
//			+ "        </score-instrument>\r\n"
//			+ "        <score-instrument id=\"P1-I45\">\r\n"
//			+ "          <instrument-name>Pedal Hi-Hat</instrument-name>\r\n"
//			+ "        </score-instrument>\r\n"
//			+ "        <score-instrument id=\"P1-I53\">\r\n"
//			+ "          <instrument-name>Chinese Cymbal 1</instrument-name>\r\n"
//			+ "        </score-instrument>\r\n"
//			+ "        <score-instrument id=\"P1-I50\">\r\n"
//			+ "          <instrument-name>Crash Cymbal 1</instrument-name>\r\n"
//			+ "        </score-instrument>\r\n"
//			+ "        <score-instrument id=\"P1-I39\">\r\n"
//			+ "          <instrument-name>Snare</instrument-name>\r\n"
//			+ "        </score-instrument>\r\n"
//			+ "        <score-instrument id=\"P1-I46\">\r\n"
//			+ "          <instrument-name>Low Tom</instrument-name>\r\n"
//			+ "        </score-instrument>\r\n"
//			+ "        <score-instrument id=\"P1-I48\">\r\n"
//			+ "          <instrument-name>Low-Mid Tom</instrument-name>\r\n"
//			+ "        </score-instrument>\r\n"
//			+ "        <score-instrument id=\"P1-I36\">\r\n"
//			+ "          <instrument-name>Bass Drum 1</instrument-name>\r\n"
//			+ "        </score-instrument>\r\n"
//			+ "        <score-instrument id=\"P1-I54\">\r\n"
//			+ "          <instrument-name>Ride Bell</instrument-name>\r\n"
//			+ "        </score-instrument>\r\n"
//			+ "        <score-instrument id=\"P1-I44\">\r\n"
//			+ "          <instrument-name>High Floor Tom</instrument-name>\r\n"
//			+ "        </score-instrument>\r\n"
//			+ "      </score-instrument>\r\n"
//			+ "      <midi-instrument>\r\n"
//			+ "        <midi-instrument id=\"P1-I52\">\r\n"
//			+ "          <midi-channel>10</midi-channel>\r\n"
//			+ "          <midi-program>1</midi-program>\r\n"
//			+ "          <midi-unpitched>52</midi-unpitched>\r\n"
//			+ "          <volume>78.7402</volume>\r\n"
//			+ "          <pan>0</pan>\r\n"
//			+ "        </midi-instrument>\r\n"
//			+ "        <midi-instrument id=\"P1-I42\">\r\n"
//			+ "          <midi-channel>10</midi-channel>\r\n"
//			+ "          <midi-program>1</midi-program>\r\n"
//			+ "          <midi-unpitched>42</midi-unpitched>\r\n"
//			+ "          <volume>78.7402</volume>\r\n"
//			+ "          <pan>0</pan>\r\n"
//			+ "        </midi-instrument>\r\n"
//			+ "        <midi-instrument id=\"P1-I47\">\r\n"
//			+ "          <midi-channel>10</midi-channel>\r\n"
//			+ "          <midi-program>1</midi-program>\r\n"
//			+ "          <midi-unpitched>47</midi-unpitched>\r\n"
//			+ "          <volume>78.7402</volume>\r\n"
//			+ "          <pan>0</pan>\r\n"
//			+ "        </midi-instrument>\r\n"
//			+ "        <midi-instrument id=\"P1-I43\">\r\n"
//			+ "          <midi-channel>10</midi-channel>\r\n"
//			+ "          <midi-program>1</midi-program>\r\n"
//			+ "          <midi-unpitched>43</midi-unpitched>\r\n"
//			+ "          <volume>78.7402</volume>\r\n"
//			+ "          <pan>0</pan>\r\n"
//			+ "        </midi-instrument>\r\n"
//			+ "        <midi-instrument id=\"P1-I45\">\r\n"
//			+ "          <midi-channel>10</midi-channel>\r\n"
//			+ "          <midi-program>1</midi-program>\r\n"
//			+ "          <midi-unpitched>45</midi-unpitched>\r\n"
//			+ "          <volume>78.7402</volume>\r\n"
//			+ "          <pan>0</pan>\r\n"
//			+ "        </midi-instrument>\r\n"
//			+ "        <midi-instrument id=\"P1-I53\">\r\n"
//			+ "          <midi-channel>10</midi-channel>\r\n"
//			+ "          <midi-program>1</midi-program>\r\n"
//			+ "          <midi-unpitched>53</midi-unpitched>\r\n"
//			+ "          <volume>78.7402</volume>\r\n"
//			+ "          <pan>0</pan>\r\n"
//			+ "        </midi-instrument>\r\n"
//			+ "        <midi-instrument id=\"P1-I50\">\r\n"
//			+ "          <midi-channel>10</midi-channel>\r\n"
//			+ "          <midi-program>1</midi-program>\r\n"
//			+ "          <midi-unpitched>50</midi-unpitched>\r\n"
//			+ "          <volume>78.7402</volume>\r\n"
//			+ "          <pan>0</pan>\r\n"
//			+ "        </midi-instrument>\r\n"
//			+ "        <midi-instrument id=\"P1-I39\">\r\n"
//			+ "          <midi-channel>10</midi-channel>\r\n"
//			+ "          <midi-program>1</midi-program>\r\n"
//			+ "          <midi-unpitched>39</midi-unpitched>\r\n"
//			+ "          <volume>78.7402</volume>\r\n"
//			+ "          <pan>0</pan>\r\n"
//			+ "        </midi-instrument>\r\n"
//			+ "        <midi-instrument id=\"P1-I46\">\r\n"
//			+ "          <midi-channel>10</midi-channel>\r\n"
//			+ "          <midi-program>1</midi-program>\r\n"
//			+ "          <midi-unpitched>46</midi-unpitched>\r\n"
//			+ "          <volume>78.7402</volume>\r\n"
//			+ "          <pan>0</pan>\r\n"
//			+ "        </midi-instrument>\r\n"
//			+ "        <midi-instrument id=\"P1-I48\">\r\n"
//			+ "          <midi-channel>10</midi-channel>\r\n"
//			+ "          <midi-program>1</midi-program>\r\n"
//			+ "          <midi-unpitched>48</midi-unpitched>\r\n"
//			+ "          <volume>78.7402</volume>\r\n"
//			+ "          <pan>0</pan>\r\n"
//			+ "        </midi-instrument>\r\n"
//			+ "        <midi-instrument id=\"P1-I36\">\r\n"
//			+ "          <midi-channel>10</midi-channel>\r\n"
//			+ "          <midi-program>1</midi-program>\r\n"
//			+ "          <midi-unpitched>36</midi-unpitched>\r\n"
//			+ "          <volume>78.7402</volume>\r\n"
//			+ "          <pan>0</pan>\r\n"
//			+ "        </midi-instrument>\r\n"
//			+ "        <midi-instrument id=\"P1-I54\">\r\n"
//			+ "          <midi-channel>10</midi-channel>\r\n"
//			+ "          <midi-program>1</midi-program>\r\n"
//			+ "          <midi-unpitched>54</midi-unpitched>\r\n"
//			+ "          <volume>78.7402</volume>\r\n"
//			+ "          <pan>0</pan>\r\n"
//			+ "        </midi-instrument>\r\n"
//			+ "        <midi-instrument id=\"P1-I44\">\r\n"
//			+ "          <midi-channel>10</midi-channel>\r\n"
//			+ "          <midi-program>1</midi-program>\r\n"
//			+ "          <midi-unpitched>44</midi-unpitched>\r\n"
//			+ "          <volume>78.7402</volume>\r\n"
//			+ "          <pan>0</pan>\r\n"
//			+ "        </midi-instrument>\r\n"
//			+ "      </midi-instrument>\r\n"
//			+ "    </score-part>\r\n"
//			+ "  </part-list>\r\n"
//			+ "  <part id=\"P1\">\r\n"
//			+ "    <measure number=\"1\">\r\n"
//			+ "      <attributes>\r\n"
//			+ "        <divisions>16</divisions>\r\n"
//			+ "        <key>\r\n"
//			+ "          <fifths>0</fifths>\r\n"
//			+ "        </key>\r\n"
//			+ "        <clef>\r\n"
//			+ "          <sign>percussion</sign>\r\n"
//			+ "          <line>2</line>\r\n"
//			+ "        </clef>\r\n"
//			+ "      </attributes>\r\n"
//			+ "      <note>\r\n"
//			+ "        <unpitched>\r\n"
//			+ "          <display-step>A</display-step>\r\n"
//			+ "          <display-octave>5</display-octave>\r\n"
//			+ "        </unpitched>\r\n"
//			+ "        <duration>8</duration>\r\n"
//			+ "        <instrument id=\"P1-I50\"/>\r\n"
//			+ "        <voice>1</voice>\r\n"
//			+ "        <type>eighth</type>\r\n"
//			+ "        <stem>up</stem>\r\n"
//			+ "        <notehead>x</notehead>\r\n"
//			+ "      </note>\r\n"
//			+ "      <note>\r\n"
//			+ "        <chord/>\r\n"
//			+ "        <unpitched>\r\n"
//			+ "          <display-step>F</display-step>\r\n"
//			+ "          <display-octave>4</display-octave>\r\n"
//			+ "        </unpitched>\r\n"
//			+ "        <duration>8</duration>\r\n"
//			+ "        <instrument id=\"P1-I36\"/>\r\n"
//			+ "        <voice>1</voice>\r\n"
//			+ "        <type>eighth</type>\r\n"
//			+ "        <stem>up</stem>\r\n"
//			+ "      </note>\r\n"
//			+ "      <note>\r\n"
//			+ "        <unpitched>\r\n"
//			+ "          <display-step>G</display-step>\r\n"
//			+ "          <display-octave>5</display-octave>\r\n"
//			+ "        </unpitched>\r\n"
//			+ "        <duration>8</duration>\r\n"
//			+ "        <instrument id=\"P1-I43\"/>\r\n"
//			+ "        <voice>1</voice>\r\n"
//			+ "        <type>eighth</type>\r\n"
//			+ "        <stem>up</stem>\r\n"
//			+ "        <notehead>x</notehead>\r\n"
//			+ "      </note>\r\n"
//			+ "      <note>\r\n"
//			+ "        <unpitched>\r\n"
//			+ "          <display-step>G</display-step>\r\n"
//			+ "          <display-octave>5</display-octave>\r\n"
//			+ "        </unpitched>\r\n"
//			+ "        <duration>8</duration>\r\n"
//			+ "        <instrument id=\"P1-I43\"/>\r\n"
//			+ "        <voice>1</voice>\r\n"
//			+ "        <type>eighth</type>\r\n"
//			+ "        <stem>up</stem>\r\n"
//			+ "        <notehead>x</notehead>\r\n"
//			+ "      </note>\r\n"
//			+ "      <note>\r\n"
//			+ "        <chord/>\r\n"
//			+ "        <unpitched>\r\n"
//			+ "          <display-step>C</display-step>\r\n"
//			+ "          <display-octave>5</display-octave>\r\n"
//			+ "        </unpitched>\r\n"
//			+ "        <duration>8</duration>\r\n"
//			+ "        <instrument id=\"P1-I39\"/>\r\n"
//			+ "        <voice>1</voice>\r\n"
//			+ "        <type>eighth</type>\r\n"
//			+ "        <stem>up</stem>\r\n"
//			+ "      </note>\r\n"
//			+ "      <note>\r\n"
//			+ "        <unpitched>\r\n"
//			+ "          <display-step>G</display-step>\r\n"
//			+ "          <display-octave>5</display-octave>\r\n"
//			+ "        </unpitched>\r\n"
//			+ "        <duration>8</duration>\r\n"
//			+ "        <instrument id=\"P1-I43\"/>\r\n"
//			+ "        <voice>1</voice>\r\n"
//			+ "        <type>eighth</type>\r\n"
//			+ "        <stem>up</stem>\r\n"
//			+ "        <notehead>x</notehead>\r\n"
//			+ "      </note>\r\n"
//			+ "      <note>\r\n"
//			+ "        <unpitched>\r\n"
//			+ "          <display-step>G</display-step>\r\n"
//			+ "          <display-octave>5</display-octave>\r\n"
//			+ "        </unpitched>\r\n"
//			+ "        <duration>8</duration>\r\n"
//			+ "        <instrument id=\"P1-I43\"/>\r\n"
//			+ "        <voice>1</voice>\r\n"
//			+ "        <type>eighth</type>\r\n"
//			+ "        <stem>up</stem>\r\n"
//			+ "        <notehead>x</notehead>\r\n"
//			+ "      </note>\r\n"
//			+ "      <note>\r\n"
//			+ "        <chord/>\r\n"
//			+ "        <unpitched>\r\n"
//			+ "          <display-step>F</display-step>\r\n"
//			+ "          <display-octave>4</display-octave>\r\n"
//			+ "        </unpitched>\r\n"
//			+ "        <duration>8</duration>\r\n"
//			+ "        <instrument id=\"P1-I36\"/>\r\n"
//			+ "        <voice>1</voice>\r\n"
//			+ "        <type>eighth</type>\r\n"
//			+ "        <stem>up</stem>\r\n"
//			+ "      </note>\r\n"
//			+ "      <note>\r\n"
//			+ "        <unpitched>\r\n"
//			+ "          <display-step>G</display-step>\r\n"
//			+ "          <display-octave>5</display-octave>\r\n"
//			+ "        </unpitched>\r\n"
//			+ "        <duration>8</duration>\r\n"
//			+ "        <instrument id=\"P1-I43\"/>\r\n"
//			+ "        <voice>1</voice>\r\n"
//			+ "        <type>eighth</type>\r\n"
//			+ "        <stem>up</stem>\r\n"
//			+ "        <notehead>x</notehead>\r\n"
//			+ "      </note>\r\n"
//			+ "      <note>\r\n"
//			+ "        <unpitched>\r\n"
//			+ "          <display-step>G</display-step>\r\n"
//			+ "          <display-octave>5</display-octave>\r\n"
//			+ "        </unpitched>\r\n"
//			+ "        <duration>8</duration>\r\n"
//			+ "        <instrument id=\"P1-I43\"/>\r\n"
//			+ "        <voice>1</voice>\r\n"
//			+ "        <type>eighth</type>\r\n"
//			+ "        <stem>up</stem>\r\n"
//			+ "        <notehead>x</notehead>\r\n"
//			+ "      </note>\r\n"
//			+ "      <note>\r\n"
//			+ "        <chord/>\r\n"
//			+ "        <unpitched>\r\n"
//			+ "          <display-step>C</display-step>\r\n"
//			+ "          <display-octave>5</display-octave>\r\n"
//			+ "        </unpitched>\r\n"
//			+ "        <duration>8</duration>\r\n"
//			+ "        <instrument id=\"P1-I39\"/>\r\n"
//			+ "        <voice>1</voice>\r\n"
//			+ "        <type>eighth</type>\r\n"
//			+ "        <stem>up</stem>\r\n"
//			+ "      </note>\r\n"
//			+ "      <note>\r\n"
//			+ "        <unpitched>\r\n"
//			+ "          <display-step>G</display-step>\r\n"
//			+ "          <display-octave>5</display-octave>\r\n"
//			+ "        </unpitched>\r\n"
//			+ "        <duration>8</duration>\r\n"
//			+ "        <instrument id=\"P1-I43\"/>\r\n"
//			+ "        <voice>1</voice>\r\n"
//			+ "        <type>eighth</type>\r\n"
//			+ "        <stem>up</stem>\r\n"
//			+ "        <notehead>x</notehead>\r\n"
//			+ "      </note>\r\n"
//			+ "    </measure>\r\n"
//			+ "    <measure number=\"2\">\r\n"
//			+ "      <attributes>\r\n"
//			+ "        <divisions>16</divisions>\r\n"
//			+ "      </attributes>\r\n"
//			+ "      <note>\r\n"
//			+ "        <unpitched>\r\n"
//			+ "          <display-step>C</display-step>\r\n"
//			+ "          <display-octave>5</display-octave>\r\n"
//			+ "        </unpitched>\r\n"
//			+ "        <duration>4</duration>\r\n"
//			+ "        <instrument id=\"P1-I39\"/>\r\n"
//			+ "        <voice>1</voice>\r\n"
//			+ "        <type>16th</type>\r\n"
//			+ "        <stem>up</stem>\r\n"
//			+ "      </note>\r\n"
//			+ "      <note>\r\n"
//			+ "        <chord/>\r\n"
//			+ "        <unpitched>\r\n"
//			+ "          <display-step>F</display-step>\r\n"
//			+ "          <display-octave>4</display-octave>\r\n"
//			+ "        </unpitched>\r\n"
//			+ "        <duration>4</duration>\r\n"
//			+ "        <instrument id=\"P1-I36\"/>\r\n"
//			+ "        <voice>1</voice>\r\n"
//			+ "        <type>16th</type>\r\n"
//			+ "        <stem>up</stem>\r\n"
//			+ "      </note>\r\n"
//			+ "      <note>\r\n"
//			+ "        <unpitched>\r\n"
//			+ "          <display-step>C</display-step>\r\n"
//			+ "          <display-octave>5</display-octave>\r\n"
//			+ "        </unpitched>\r\n"
//			+ "        <duration>4</duration>\r\n"
//			+ "        <instrument id=\"P1-I39\"/>\r\n"
//			+ "        <voice>1</voice>\r\n"
//			+ "        <type>16th</type>\r\n"
//			+ "        <stem>up</stem>\r\n"
//			+ "      </note>\r\n"
//			+ "      <note>\r\n"
//			+ "        <unpitched>\r\n"
//			+ "          <display-step>C</display-step>\r\n"
//			+ "          <display-octave>5</display-octave>\r\n"
//			+ "        </unpitched>\r\n"
//			+ "        <duration>4</duration>\r\n"
//			+ "        <instrument id=\"P1-I39\"/>\r\n"
//			+ "        <voice>1</voice>\r\n"
//			+ "        <type>16th</type>\r\n"
//			+ "        <stem>up</stem>\r\n"
//			+ "      </note>\r\n"
//			+ "      <note>\r\n"
//			+ "        <unpitched>\r\n"
//			+ "          <display-step>C</display-step>\r\n"
//			+ "          <display-octave>5</display-octave>\r\n"
//			+ "        </unpitched>\r\n"
//			+ "        <duration>4</duration>\r\n"
//			+ "        <instrument id=\"P1-I39\"/>\r\n"
//			+ "        <voice>1</voice>\r\n"
//			+ "        <type>16th</type>\r\n"
//			+ "        <stem>up</stem>\r\n"
//			+ "      </note>\r\n"
//			+ "      <note>\r\n"
//			+ "        <unpitched>\r\n"
//			+ "          <display-step>E</display-step>\r\n"
//			+ "          <display-octave>5</display-octave>\r\n"
//			+ "        </unpitched>\r\n"
//			+ "        <duration>4</duration>\r\n"
//			+ "        <instrument id=\"P1-I48\"/>\r\n"
//			+ "        <voice>1</voice>\r\n"
//			+ "        <type>16th</type>\r\n"
//			+ "        <stem>up</stem>\r\n"
//			+ "      </note>\r\n"
//			+ "      <note>\r\n"
//			+ "        <unpitched>\r\n"
//			+ "          <display-step>E</display-step>\r\n"
//			+ "          <display-octave>5</display-octave>\r\n"
//			+ "        </unpitched>\r\n"
//			+ "        <duration>4</duration>\r\n"
//			+ "        <instrument id=\"P1-I48\"/>\r\n"
//			+ "        <voice>1</voice>\r\n"
//			+ "        <type>16th</type>\r\n"
//			+ "        <stem>up</stem>\r\n"
//			+ "      </note>\r\n"
//			+ "      <note>\r\n"
//			+ "        <unpitched>\r\n"
//			+ "          <display-step>D</display-step>\r\n"
//			+ "          <display-octave>5</display-octave>\r\n"
//			+ "        </unpitched>\r\n"
//			+ "        <duration>4</duration>\r\n"
//			+ "        <instrument id=\"P1-I46\"/>\r\n"
//			+ "        <voice>1</voice>\r\n"
//			+ "        <type>16th</type>\r\n"
//			+ "        <stem>up</stem>\r\n"
//			+ "      </note>\r\n"
//			+ "      <note>\r\n"
//			+ "        <unpitched>\r\n"
//			+ "          <display-step>D</display-step>\r\n"
//			+ "          <display-octave>5</display-octave>\r\n"
//			+ "        </unpitched>\r\n"
//			+ "        <duration>4</duration>\r\n"
//			+ "        <instrument id=\"P1-I46\"/>\r\n"
//			+ "        <voice>1</voice>\r\n"
//			+ "        <type>16th</type>\r\n"
//			+ "        <stem>up</stem>\r\n"
//			+ "      </note>\r\n"
//			+ "      <note>\r\n"
//			+ "        <unpitched>\r\n"
//			+ "          <display-step>A</display-step>\r\n"
//			+ "          <display-octave>5</display-octave>\r\n"
//			+ "        </unpitched>\r\n"
//			+ "        <duration>32</duration>\r\n"
//			+ "        <instrument id=\"P1-I50\"/>\r\n"
//			+ "        <voice>1</voice>\r\n"
//			+ "        <type>half</type>\r\n"
//			+ "        <stem>up</stem>\r\n"
//			+ "        <notehead>x</notehead>\r\n"
//			+ "      </note>\r\n"
//			+ "      <note>\r\n"
//			+ "        <chord/>\r\n"
//			+ "        <unpitched>\r\n"
//			+ "          <display-step>F</display-step>\r\n"
//			+ "          <display-octave>4</display-octave>\r\n"
//			+ "        </unpitched>\r\n"
//			+ "        <duration>32</duration>\r\n"
//			+ "        <instrument id=\"P1-I36\"/>\r\n"
//			+ "        <voice>1</voice>\r\n"
//			+ "        <type>half</type>\r\n"
//			+ "        <stem>up</stem>\r\n"
//			+ "      </note>\r\n"
//			+ "    </measure>\r\n"
//			+ "  </part>\r\n"
//			+ "</score-partwise>\r\n"
//			+ "";
//	public ParserConsole() {
//
//	}
//
//	public static void main(String[] args) throws ParserConfigurationException, ValidityException, ParsingException, IOException {
//
//
//
//
//		try {
//			//making the DOC
//			DocumentBuilderFactory dbFactory = DocumentBuilderFactory.newInstance();
//			DocumentBuilder dBuilder = dbFactory.newDocumentBuilder();
//
//			//used as an input for dBuilder.parse() instead of inputting a file
//			InputSource is = new InputSource();
//			is.setCharacterStream(new StringReader(xmlString));
//
//			//input is
//			Document doc = dBuilder.parse(is);
//
//			//better Visual
//			doc.getDocumentElement().normalize();
//
//			//get all nodes in doc
//			NodeList nodesList1 = doc.getElementsByTagName("*");
//
//			//iterate and print nodes
//			for (int i = 0; i < nodesList1.getLength(); i++) {
//				Node node = nodesList1.item(i);
//
//				Element element = (Element) node;
//				System.out.println(element.getNodeName());
//
//				String name = element.getAttribute("name");
//				System.out.println(name);
//			}
//		}
//		catch (Exception e) {
//			e.printStackTrace();
//		}
//
//		ObjectMapper objMapper = new XmlMapper();
//		ScorePartwise value;
//
//
//		if(xmlString.contains("Guitar")) {
//			String xmlG = xmlString;
//			//(Guitar) replace xml Node name with Java Object already created
//			//originally <noteBefore>, prof changed to <note>, here change to <noteAfter>
//			xmlG = xmlG.replace("note", "noteAfter");
//			try {
//				value = objMapper.readValue(xmlG, ScorePartwise.class);
//			} catch (JsonProcessingException e) {
//				e.printStackTrace();
//			}
//		}
//		else if(xmlString.contains("Drumset")) {
//			String xmlD = xmlString;
//			//(Drum) replace xml Node name with Java Object already created
//			//originally <noteBefore> , prof changed to <note>, here change to <
//			//           <notehead>
//			xmlD = xmlD.replace("note", "noteBefore");
//			xmlD = xmlD.replace("noteBeforehead", "notehead");
//			try {
//				value = objMapper.readValue(xmlD, ScorePartwise.class);
//			} catch (JsonProcessingException e) {
//				e.printStackTrace();
//			}
//		}
//
////		playMusic();
//			MusicXmlParser parser = new MusicXmlParser();
//			MusicXmlParserListener listener = new MusicXmlParserListener();
//			LilyPondParserListener lilyListener = new LilyPondParserListener();
//			MidiParserListener midiListener = new MidiParserListener();
//			StaccatoParserListener stac = new StaccatoParserListener();
//
//
//			parser.addParserListener(listener);
//			parser.addParserListener(lilyListener);
//			parser.addParserListener(midiListener);
//			parser.addParserListener(stac);
//
//			parser.parse(drum);
//			System.out.println("got past parser");
//
//			Player player = new Player();
//
//			String musicXmlPattern = listener.getMusicXMLString();
//			String secondPattern = lilyListener.getLyString();
//			Sequence third = midiListener.getSequence();
//			Pattern stacfinal = stac.getPattern().atomize();
//
//
//			player.play(musicXmlPattern);
//			player.play(secondPattern);
//			player.play(third);
//			player.play(stacfinal);
//
//
//
//	}
//	public static void playMusic() {
//		try {
//			MusicXmlParser parser = new MusicXmlParser();
//			MusicXmlParserListener listener = new MusicXmlParserListener();
//			LilyPondParserListener lilyListener = new LilyPondParserListener();
//			MidiParserListener midiListener = new MidiParserListener();
//
//
//			parser.addParserListener(listener);
//			parser.addParserListener(lilyListener);
//			parser.addParserListener(midiListener);
//
//			parser.parse(drum);
//			System.out.println("got past parser");
//
//			Player player = new Player();
//			String musicXmlPattern = listener.getMusicXMLString();
//			player.play(musicXmlPattern);
//		}catch (Exception e) {
//
//		}
//	}
//
//}
//
